# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18N38ILNQgRD-82ReVmVt5atNYmViWicA
"""

import tensorflow as tf
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

